### ISSUE TITLE
Connecting to Jolokia agent with basic auth fails using Connect/Remote tab

### ISSUE THREAD

**Issue by openet** [hawtio/hawtio#1643]
I am attaching jolokia to JVM with user name and password (basic auth mode). When I press play button on Connect/Discovery tab Hawtio works fine it asks for login/passwd and connects. However, when I try to use Connect/Remote form Hawtio opens a blank page. 
I run exactly the following command on Red Hat 6.3 running as VM on Windows 7 as a host.
`java -jar hawtio-app-1.4.16.jar` 
and 
`java -jar jolokia-jvm-1.2.2-agent.jar --user dupa --password jasio toggle 4644 --host x.x.x.x --port 1122`
I experience the same behavior in Firefox 32.0.3 (Red Hat 6.3), Firefox 32.0.3 (Windows 7) and Chrome 37.0.2062.124 (Windows 7)

**Added on 10 Oct 2014**
The issue in NOT visible on version 1.4.21 and 1.4.24 (just remember to tick 'use proxy' box in Web UI).
However, for versions 1.4.21 and 1.4.24 Discovery does not find the agents (in the same environment 1.4.16 works fine).

**Comment by rlodge** [comment]
I'm not sure I have the same issue or not.  I have one tomcat running jolokia, secured by basic auth.  When I start another to run hawtio (it doesn't seem to matter if I use the war or the jar), fill out the connect information for the first tomcat, including username and password, and then press "Connect to remote server", the new tab has some of the correct information displayed (e.g. it displays the JMX bean tree, etc.), but no attributes, charts, methods, etc. are ever shown.

Under the covers requests fail to Jolokia with 401 unauthorized errors.  The browser reports an additional problem with Access-Control-Allow-Origin header, but this is a red herring, as the jolokia tomcat's access logs are reporting 401 errors; I think the CORS headers just don't get added by jolokia because the request never reaches jolokia itself.

I'm not sure I fully understand what's going on, but on subsequent ajax calls the beforeSend call finds a "null" as the username on the userDetails object.  I'm not sure exactly how that happens, or where it's mutated, but it gets set to null and the header is then not constructed correctly.

I can fix either by changing the closure to on line 66 to read:

```
xhr.setRequestHeader('Authorization', Core.getBasicAuthHeader(<string>username, <string>password));
```

so that subsequent calls don't pick up any changes to the singleton.

Or I can add, on line 60 or so:

```
jolokiaParams['username'] = username;
jolokiaParams['password'] = password;
```

so that the jolokia will just use those values from then on.  I guess this is my preferred solution, as jQuery recommends not using ajaxSetup anyway and it seems to use the jolokia api the "correct" way.

I can if desired submit a pull request for this, if I'm on the right bug and my preferred approach is workable.

**Comment by davsclaus** [comment]
Try again with latest release

**Comment by davsclaus** [comment]
I just tried and it works in the next release.
