### ISSUE TITLE
Camel Context not auto-discovered

### ISSUE THREAD

**Issue by covolution** [hawtio/hawtio#1712]
I have Camel running in my JVM and hawtio connected to it.  I can see Camel details in the hawtio JMX tab but the Camel plugin doesn't seem to work.

How is the camel context auto-discovered?  Can it be configured?
I'm using:
`<camel:jmxAgent id="agent" mbeanObjectDomainName="My.Camel" statisticsLevel="RoutesOnly" />`

**Comment by yazun** [comment]
Is there a way to define a custom jmxDomain for activemq?

**Comment by davsclaus** [comment]
No not in hawtio

**Comment by yazun** [comment]
We would appreciate to add it as a future milestone, similarly to https://github.com/hawtio/hawtio/issues/1755
Or more general solution could be added for any plugin with custom jmxDomain. 
Could you explain where jmxDomain is defined? - it's referenced in the plugin's source code:
https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/activemq/js/activemqPlugin.ts , so maybe redefining it there would be enough?

**Comment by davsclaus** [comment]
Yeah hopefully that would be the only change, but we haven't tried with different domain. 

Why are you btw using a different domain for the AMQ broker?

**Comment by yazun** [comment]
The reason to use JMX was to delete the queues - in our (debtatable) model we have queues created per (processing) run by a coordinator process and jmx was the way to delete them by the coordinator process after processing nodes (spawned in the batch system) finished using them. Other methods of queue cleanup did not work somehow (we tried expiration of the queues, not sure if advisory messages too). If you have hints how to do this without jmx, it would be good to hear!

Developer introduced a custom values for jmxDomainName in activemq config, probably to make explicit reference later in the coordinator. Since such values could be changed in the activemq config I believe it should be configurable in the toolset around it. Other option would be to disable custom name in the activemq.
FYI: we use both activemq and camel (we got your book into our library too) for variability studies in our project:
http://sci.esa.int/gaia/28820-summary/
Cheers,
Krzysztof

**Comment by davsclaus** [comment]
Yeah we could maybe have a preference for activemq, where people can configure the name of the domain?

**Comment by yazun** [comment]
Yes, this would do.

**Comment by davsclaus** [comment]
Okay I have just implemented this. See that ticket above

**Comment by davsclaus** [comment]
I wonder how many places this requires to change to support this for Camel also?

**Comment by yazun** [comment]
thanks for implementing!
