### ISSUE TITLE
Support for service discovery / server side saved sessions

### ISSUE THREAD

**Issue by davidkarlsen** [hawtio/hawtio#2268]
See this thread: http://stackoverflow.com/questions/26541322/hawtio-server-side-saved-connections.

It would be great if servers could be defined through a custom Discovery class and/or via files in .hawtio config

**Comment by dcowden** [comment]
+1 for this.

In our case we have 100's of JVMs, and we have enabled all of our JVMs with jolokia already ( in AWS via CloudFormation and in Kubernetes via Docker base images).

What we need to to make hawt.io even hawter is to allow a discovery plugin so that we can discover active JVMs.  A static list doesnt add much value, because EC2 instance/containers are coming and going.

I envision it working this way:

   * A ConnectionDiscovery class allows generally the ability to pre-populate connections for users
   * Several implementations are available:
         * AWS-- given that the host running hawt has the right IAM role, we query all AWS nodes having a given tag ( like JVM)
        * Kubernetes-- we query the kubernetes api server to list nodes with a given tag ( again, JVM)
        * a LocalStorage class simply reads/writes new connections onto the server somewhere
        * a DatabaseDiscovery class uses a database

This would make hawt.io incredibly powerful in container and aws ecosystems!
