### ISSUE TITLE
Upgrade to Camel 2.19

### ISSUE THREAD

**Issue by davsclaus** [hawtio/hawtio#2296]
When its released we should upgrade to this version and get a new release of hawtio out the door as well

**Comment by tadayosi** [comment]
Probably it's good time to release hawtio 1.5.1 after that.

**Comment by davsclaus** [comment]
The maven plugin that generates the hawtio model seems to have a glitch which we need to find out why

**Comment by davsclaus** [comment]
```
-      "acceptInput": "true",
-      "acceptOutput": "true",
+      "acceptInput": "null",
+      "acceptOutput": "null",
```

**Comment by davsclaus** [comment]
Okay got it fixed now

**Comment by skarsaune** [comment]
I get an error building hawtio-web with mvn that did not happen before.

I notice that the same file is affected, but is it related to this or should I register a separate issue?

After running git status shows that src/main/webapp/lib/camelModel.js is modified, and a diff shows quite substantial changes to that file after building. 

Are  there any options to  be specified to avoid this?

mvn:

mvn clean install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building hawtio-web 1.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for com.google.guava:guava:jar:${guava.version} is missing, no dependency information available
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ hawtio-web ---
[INFO] Deleting /Users/marska/Documents/dev/hawtio/hawtio-web/target
[INFO] Deleting /Users/marska/Documents/dev/hawtio/hawtio-web/src/main/webapp/bower_components (includes = [], excludes = [])
[INFO] Deleting /Users/marska/Documents/dev/hawtio/hawtio-web/src/main/webapp/app (includes = [app.js, app.min.js, *.map], excludes = [])
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-java-version) @ hawtio-web ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven-version) @ hawtio-web ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create-timestamp (get-build-timestamp) @ hawtio-web ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.2:create (get-scm-revision) @ hawtio-web ---
[INFO] Checking for local modifications: skipped.
[INFO] Updating project files from SCM: skipped.
[INFO] Executing: /bin/sh -c cd /Users/marska/Documents/dev/hawtio/hawtio-web && git rev-parse --verify HEAD
[INFO] Working directory: /Users/marska/Documents/dev/hawtio/hawtio-web
[INFO] Storing buildNumber: bc1a878776f2b4fd6ad86eacc8f561abe7819ff9 at timestamp: 1495386669960
[INFO] Executing: /bin/sh -c cd /Users/marska/Documents/dev/hawtio/hawtio-web && git rev-parse --verify HEAD
[INFO] Working directory: /Users/marska/Documents/dev/hawtio/hawtio-web
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- hawtio-json-schema-generator-plugin:1.5-SNAPSHOT:generate-json-schema (default) @ hawtio-web ---
[INFO] Looking up schema for class io.hawt.dozer.schema.Field
[INFO] Looking up schema for class io.hawt.dozer.schema.FieldExclude
[INFO] Looking up schema for class io.hawt.dozer.schema.Mapping
[INFO] Looking up schema for class io.hawt.dozer.schema.Mappings
[INFO] 
[INFO] --- hawtio-json-schema-generator-plugin:1.5-SNAPSHOT:generate-camel-model (default) @ hawtio-web ---
[INFO] Assembling Camel model schema
[INFO] Using Apache Camel 2.19.0
[INFO] Assembled Camel models into combined schema: /Users/marska/Documents/dev/hawtio/hawtio-web/src/main/webapp/lib/camelModel.js
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:install-node-and-npm (install node and npm) @ hawtio-web ---
[INFO] Node v0.10.32 is already installed.
[INFO] Found NPM version 1.4.12
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:npm (npm install) @ hawtio-web ---
[INFO] Running 'npm install --color=false' in /Users/marska/Documents/dev/hawtio/hawtio-web
[ERROR] npm WARN package.json batch@0.5.0 No repository field.
[ERROR] npm WARN package.json bytes@0.2.1 No repository field.
[ERROR] npm WARN package.json cookie-signature@1.0.1 No repository field.
[ERROR] npm WARN package.json dateformat@1.0.2-1.2.3 No repository field.
[ERROR] npm WARN package.json pause@0.0.1 No repository field.
[ERROR] npm WARN package.json range-parser@0.0.4 No repository field.
[ERROR] npm WARN package.json string_decoder@0.10.31 string_decoder is also the name of a node core module.
[ERROR] npm WARN package.json uid2@0.0.3 No repository field.
[INFO] 
[INFO] > hawtio-web@1.5.1 install /Users/marska/Documents/dev/hawtio/hawtio-web
[INFO] > node node_modules/protractor/bin/webdriver-manager update
[INFO] 
[INFO] selenium standalone is up to date.
[INFO] chromedriver is up to date.
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.24:grunt (grunt build) @ hawtio-web ---
[INFO] Running 'grunt default --no-color' in /Users/marska/Documents/dev/hawtio/hawtio-web
[INFO] Building hawt.io
[INFO] 
[INFO] Running "bower:install" (bower) task
[INFO] >> Installed bower packages
[INFO] 
[INFO] Running "wiredep:target" (wiredep) task
[INFO] 
[INFO] Running "typescript:base" (typescript) task
[INFO] File src/main/webapp/app/app.js created.
[INFO] js: 1 file, map: 1 file, declaration: 1 file (3566ms)
[INFO] 
[INFO] Running "rename:declaration" (rename) task
[INFO] 
[INFO] Running "karma:unit" (karma) task
[INFO] PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR: 'No Cubism definition found. Please include jolokia.js and cubism.js before jolokia-cubism.js'
[INFO] 
[INFO] PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR: 'No Jolokia definition found. Please include jolokia.js before jolokia-simple.js'
[INFO] 
[INFO] WARN [web-server]: 404: /jolokia
[INFO] WARN [web-server]: 404: /jolokia
[INFO] WARN [web-server]: 404: /plugin
       PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 83 SUCCESS (0 secs / 0 secs)
       INFO: 'Jasmine version used by karma-jasmine: 1.3.1 revision 1354556913'
       PhantomJS 2.1.1 (Mac OS X 0.0.0) Forms camel model has inheritence FAILED
[INFO] 	Expected 'null' to equal 'string'.
       PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 83 of 83 (1 FAILED) (0.048 secs / 0.047 secs)
[INFO] Warning: Task "karma:unit" failed. Use --force to continue.
[INFO] 
[INFO] Aborted due to warnings.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.381 s
[INFO] Finished at: 2017-05-21T19:11:25+02:00
[INFO] Final Memory: 36M/499M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.24:grunt (grunt build) on project hawtio-web: Failed to run task: 'grunt default --no-color' failed. (error code 3) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by skarsaune** [comment]
Ah, never mind. works when I explicitly build the json-generator first
