### ISSUE TITLE
Can HawtIO's login module be replaced ?

### ISSUE THREAD

**Issue by yogeshrao** [hawtio/hawtio#2396]
Hi,

I am looking at a requirement where I see HawtIO's login module needs to be replaced ( I understand HawtIO uses JAAS, unfortunately it still isn't going to help me), can I replace HawtIO's login module with a custom one? If yes then how can i do it and any precautions for the same?

Regards,
-Yogesh

**Comment by tadayosi** [comment]
Have you looked at the configuration guide?
http://hawt.io/configuration/index.html
There are a plenty of explanations on how to configure your login module in the doc.

**Comment by yogeshrao** [comment]
@tadayosi I was looking at changing the entire login module of HawtIO which includes the HTML content, auth mechanism. The configuration only talks of changing auth mechanism (by writing a custom JAAS ) which i have already pointed out.

**Comment by tadayosi** [comment]
No response for long time made me think your problem was solved. Now I don't feel I really understand what you are trying to do, but probably the answer is simply no. hawtio is not designed to be able to replace JAAS with other auth mechanisms. Of course, hawtio's JAAS mechanism is mostly implemented by the servlet filters and servlets defined in web.xml, so theoretically you can completely throw them away and build your own implementations with a full scratch web.xml to introduce your own one.

One more thing to note here is that hawtio also provides an integration with Keycloak. If you're just satisfied with Keycloak then you can use Keycloak instead of the default JAAS auth.
