### ISSUE TITLE
hawtio-app: investigate warnings logged by maven-assembly-plugin

### ISSUE THREAD

**Issue by abkieling** [hawtio/hawtio#2546]
Maven output:

```
[INFO] --- maven-assembly-plugin:3.1.0:single (make-assembly) @ hawtio-app ---
[INFO] Reading assembly descriptor: src/main/assembly/assembly.xml
[WARNING] NOTE: Your assembly specifies a dependencySet that matches multiple artifacts, but specifies a concrete output format. THIS MAY RESULT IN ONE OR MORE ARTIFACTS BEING OBSCURED!

Output directory: ''
Output filename mapping: ''
[WARNING] Artifact: io.hawt:hawtio-app:jar:2.4-SNAPSHOT references the same file as the assembly destination file. Moving it to a temporary location for inclusion.
[INFO] Building jar: /home/akieling/dev/projects/hawtio/hawtio-app/target/hawtio-app-2.4-SNAPSHOT.jar
[WARNING] Configuration option 'appendAssemblyId' is set to false.
Instead of attaching the assembly file: /home/akieling/dev/projects/hawtio/hawtio-app/target/hawtio-app-2.4-SNAPSHOT.jar, it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[WARNING] Replacing pre-existing project main-artifact file: /home/akieling/dev/projects/hawtio/hawtio-app/target/archive-tmp/hawtio-app-2.4-SNAPSHOT.jar
with assembly file: /home/akieling/dev/projects/hawtio/hawtio-app/target/hawtio-app-2.4-SNAPSHOT.jar
```

**Comment by wlei07** [comment]
The fix works out fine, however, it gives the following "warnings", which, I think should be of "info" level as they are expected:

[WARNING] Artifact: com.zetes.eid.lot2.ecitizen:event-manager-event-and-mapper:jar:2.0.0-SNAPSHOT references the same file as the assembly destination file. Moving it to a temporary location for inclusion.
[WARNING] Configuration option 'appendAssemblyId' is set to false.
Instead of attaching the assembly file: ..., it will become the file for main project artifact.
NOTE: If multiple descriptors or descriptor-formats are provided for this project, the value of this file will be non-deterministic!
[WARNING] Replacing pre-existing project main-artifact file: ...
with assembly file: C:\Users\lei.wang\dev\event-manager-event-and-mapper\target\event-manager-event-and-mapper-2.0.0-SNAPSHOT.jar
