### ISSUE TITLE
How can we customize hawtio layout? 

### ISSUE THREAD

**Issue by hungbang** [hawtio/hawtio#2640]
I had a spring-boot app, so now I wanna use Hawtio to enable JMX console. Yes, it works, but my question is how can I customize the layout? something like Title, enable or disable something needed.

Thank you in advance, it's not a bug, just a question when this is the first time I apply Hawtio :)

**Comment by tadayosi** [comment]
Welcome to the Hawtio community :-)
Hawtio provides some UI customisations with `hawtconfig.json`:
https://github.com/hawtio/hawtio/tree/master/examples/springboot-authentication#hawtconfigjson-customisation
App title, logo, favicon, login texts, and a bit of styles are what you can customise. The layout is not customisable unfortunately, mainly due to the limitation of the underlying PatternFly framework.

**Comment by hungbangevizi** [comment]
Thank you for your support. @tadayosi , let me take a look at the example, I hope it can solve my problem.
