### ISSUE TITLE
Potential Refactoring Estimate

### ISSUE THREAD

**Issue by alvintanjianjia** [hawtio/hawtio#2752]
**Summary**
I have identified a few classes with refactoring potential along with its estimated time to refactor, specifically AuthenticationFilter.java. The estimated time is based on historical commits containing refactoring and the complexity of the involved classes. The class was refactored once on Sep 11, 2017  along with other classes in commit 8cb970a75b4c59a1668a3571191aaca88f76dcb2. Given the duration of the last refactoring, could it be possible to improve this class further? I am probably not qualified and experienced enough to point out the exact code needs to be refactored, given my limited knowledge of the project and codebase.

**Urgency**
Low priority. For maintenance of code in the long run.

Hi,
I am currently doing some research on Estimating Time Taken for Software Refactoring. Hawtio is one of my case studies being a highly popular project. Would appreciate your kind feedback on the appropriateness of the estimated time to refactor. 
I am specifically looking at potential for refactoring, such as breaking functions that are too long into shorter functions, or to remove code duplication. Would you agree that there could be some modification to the code to make it better in the listed classes? And if so, is the estimated time appropriate to carry out the improvement? I will be grateful for any help you can provide.

1. AuthenticationFilter.java - 4 hours
2. SessionExpiryFilter.java - 2 hours

Thank you.

Regards,
Alvin

**Comment by tadayosi** [comment]
Time estimations for refactoring aren't meaningful without actual context, e.g. why you do refactoring, what bug fixes/feature enhancements you want to achieve upon the refactored code, whether there are already some test harnesses that make the refactoring safe, etc.

Instead of asking us, what about just trying to refactor the code yourself and measure the time it takes?  It will give you more insights on refactoring and the research you are conducting.
