### ISSUE TITLE
E2E - Downsize matrix for E2E testing

### ISSUE THREAD

**Issue by tadayosi** [hawtio/hawtio#2887]
Right now, the matrix combination is 2 (Java 11, 17) x 2 (springboot, quarkus) x 2 (chrome, firefox) = 8. But since the e2e tests are getting unstable, the whole E2E check has gotten flaky and unreliable. Probably we should downsize it to mitigate the chance of flaky results. For example, for Java 17 we should probably fully test it only with a single browser (e.g. Chrome) and it might be sufficent to run the full combination only for Java 11 (the default LTS version we target). (But it can still only downsize the number to 6.)

**Comment by tadayosi** [comment]
cc @mmuzikar

**Comment by mmuzikar** [comment]
I think most of the flakiness is again due to some issues with chrome driver randomly crashing. What sucks is that it's hard to reproduce, some sources say that increasing the shm for the docker container fixes it but it didn't fix it in our case, we can try to disable the shm usage if that stabilizes the chrome browser.

**Comment by tadayosi** [comment]
Now the CI seems to get stabilised again with #2877. Let's close this for now. Thanks @mmuzikar!
