### ISSUE TITLE
Repeated open / close of connection lost toast alert 

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/hawtio#2919]
The 'Connection lost' toast alert seems to rapidly open / close with every retry, making it look a bit strange.

**Comment by tadayosi** [comment]
Thanks. It's because with the new PF4 it's a bit trickier to handle overlaps between toasters on retries. For Hawtio v2, the toaster popup logic is almost the same, but it just looks staying open because the time lags between open and close are very short; you'll still see flickerings with Hawtio v2 toasters sometimes, but it's just far rare to happen.

To fix this issue, we should revisit the toaster popup logic and force it to stay open until the connection failure is resolved.
