### ISSUE TITLE
Hawtio custom UI resources are blocked when using Keycloak

### ISSUE THREAD

**Issue by mmuzikar** [hawtio/hawtio#2923]
When using keycloak with custom styling style resources get blocked because of wrong MIME type: 
```
The resource from “http://localhost:10001/app.css” was blocked due to MIME type (“application/json”) mismatch (X-Content-Type-Options: nosniff). connect
```

Even when clearing out the `X-Content-Type-Options` in the Realm security defenses doesn't help.

Reproducer can be found here https://github.com/mmuzikar/hawtio/tree/HAWNG-71/tests/springboot, run `mvn spring-boot:run  -Pkeycloak` and `./run-keycloak.sh` from `examples/keycloak-intergration`

**Comment by tadayosi** [comment]
@mmuzikar Does it happen only with Spring Boot, or with Quarkus as well?

**Comment by mmuzikar** [comment]
Looks like Quarkus is working fine.

With https://github.com/hawtio/hawtio/pull/2926 `app.css` gets loaded on SB but `img/hawtio-logo.svg` still doesn't get loaded

**Comment by tadayosi** [comment]
> With #2926 `app.css` gets loaded on SB but `img/hawtio-logo.svg` still doesn't get loaded

Yes, I noticed the same issue. It looks like `img/hawtio-logo.svg` is initially loaded before Keycloak redirects to the login page, thus on browser it's cached as a broken resource. We need to either make those static resources public and accessible even under Keycloak protection, or sort out the order of resources fetching so that the logo isn't redirected background before authentication.
