### ISSUE TITLE
I would like to use Hawtio standalone

### ISSUE THREAD

**Issue by mikadev** [hawtio/hawtio#3312]
Hello i would like to use hawtio standalone jar or zip file why is it not available i don't use jbang openshift spring boot or quarkus

**Comment by grgrzybek** [comment]
Please refer to https://hawt.io/docs/get-started.html#_deploying_on_a_servlet_container. You can simply download (or build) https://github.com/hawtio/hawtio/releases/download/hawtio-3.0.1/hawtio-war-3.0.1.war and drop it into JavaEE Servlet container of your choice.

WAR (JavaEE) was the first deployment method since the project started and it's still (and will always be) supported.

**Comment by mikadev** [comment]
thanks for your answer but maybe it will be nice to have a zip (or even a jar) like all other open source project (i would like to control the installation myself)
