### ISSUE TITLE
[Camel] After upgrade hawtio from 2.17.4 to 4.0.0, the camel route diagram cannot display the id as the node name.

### ISSUE THREAD

**Issue by gbgbapsps2** [hawtio/hawtio#3460]
Hawtio version: 4.0.0

Here is the camel route xml dsl, id property is set.
![image](https://github.com/hawtio/hawtio/assets/100194896/13cfbfbc-57f1-4e55-997c-6ed7818fedf8)

But the id information doesn't show on the route diagram. It only shows the camel component's name rather than the id.
In this case, it should show 'choice3' as same as previous version <Hawtio 2.17.4>.
![image](https://github.com/hawtio/hawtio/assets/100194896/90ac34fb-3241-4609-9362-84edba0912c1)

![image](https://github.com/hawtio/hawtio/assets/100194896/c7df227f-0ea4-4819-8679-216072deada7)

**Comment by tadayosi** [comment]
Hi, thanks for your reporting.

@mmelko Do you think you can fix the issue?

**Comment by mmelko** [comment]
@gbgbapsps2 
I have to double-check but this seems to be a intentional change. Is it important to you to see actual ID of the choise step? For example also when,bean and to has it's IDs and it's not visualised even in the 2.x hawtio.   

If we will add id for the choice do we want to add it for all of the steps like to, bean etc. ?

**Comment by gbgbapsps2** [comment]
@mmelko Yes. I think it is better to show its id (if present in route) instead of the component name in the Route Diagram. Because id is an unique identifier and provide more precise information of the component node. If we only show the component name in Route Diagram, it may let the Route Diagram lose its meaning and merit. Thanks for your help.
