### ISSUE TITLE
ActiveMQ plugin broken after first use

### ISSUE THREAD

**Issue by rkettelerij** [hawtio/hawtio#623]
I've encountered a strange issue when using hawt.io with ActiveMQ. I have an application which embeds ActiveMQ and starts a Jetty server with hawt.io.

When I start my application for the first time and open hawt.io I can happily view and browse my ActiveMQ queues. Notice the 'browse' button in the picture below as well as the list of attributes and the icon in front of "myqueue".
![good](https://f.cloud.github.com/assets/291572/1298379/e6977dec-30f2-11e3-8e71-fd3978ade217.png)

So far so good. Now when I restart my application (terminate the JVM) and reopen hawt.io (refresh/restart the browser) the ActiveMQ view is messed up. I can't browse my queues (browse button is gone), no attributes are shown and also notice there's no icon in front of "myqueue":
![bad](https://f.cloud.github.com/assets/291572/1298481/4d680126-30f4-11e3-928b-4c7ba46e4598.png)

When I delete the ActiveMQ data directory and restart my application everything is fine again. So the hawt.io ActiveMQ plugin only seems to work on first use and breaks after first usage of ActiveMQ, even if there aren't any messages exchanged. 

I've provided an example application to reproduce this issue: https://github.com/rkettelerij/hawtio-issue.
## Steps to reproduce:
- `git clone https://github.com/rkettelerij/hawtio-issue`
- `cd hawtio-issue`
- `mvn clean package exec:java`
- open hawt.io: http://localhost:8180/hawtio
- navigate to ActiveMQ tab and verify everything is looking good
- terminate application/maven
- `mvn exec:java` (don't clean)
- open hawt.io: http://localhost:8180/hawtio
- navigate to ActiveMQ tab an verify you can't browse any queue's etc.

**Comment by carolosf** [comment]
I have also seen this issue - I think it is a problem with ActiveMQ when using KahaDB. To reproduce you need to look at the queues in hawt.io before any messages have been sent. This gets ActiveMQ into a strange state where it can't create the MBeans and the only way to fix it is to stop ActiveMQ, delete the ActiveMQ data directory, start ActiveMQ then send a message through and only after the message has been sent view the queues in hawt.io.

**Comment by gashcrumb** [comment]
It'd probably be good to raise an issue against ActiveMQ for that
behavior...

**Comment by bruno-teixeira-araujo** [comment]
Just in case anyone has a similar issue as the one that I've found.
In my case the issue was not with hawt.io but only with ActiveMQ.

I'm using a Spring Boot (1.5.8) with Apache Camel (2.20.1) and ActiveMQ (5.14.5) with persistence (KahaDB).
The very first time I start the server, all Queues show properly as MBeans on hawt.io and on VisualVM.
After restarting the server, Queues show as folders on both sides.
If I remove activemq-data folder and start server again, everything works properly again.

The problem was with the default JMX port that ActiveMQ uses, it was clashing with one of my processes. 
When that happens org.apache.activemq.broker.jmx.ManagementContext executes a stop and unregister some ActiveMQ's MBeans without registering them again.
