### ISSUE TITLE
browse Object/Map message payloads

### ISSUE THREAD

**Issue by jstrachan** [hawtio/hawtio#655]
when this mbean method is available we should use it for viewing ObjectMessages
https://issues.apache.org/jira/browse/AMQ-4817

**Comment by dawogfather** [comment]
Why'd you close this may I ask? 
Is there no chance of this issue being resolved?

**Comment by alexkieling** [comment]
I've reopened it. Would you be able to contribute a fix for it?

**Comment by dawogfather** [comment]
happy to try if someone points me in a direction

**Comment by tadayosi** [comment]
FWIW, now the code for browsing ActiveMQ messages is here:
https://github.com/hawtio/hawtio-integration/blob/master/plugins/activemq/ts/browse.ts

However I think first we need to add a feature at server-side, i.e. https://issues.apache.org/jira/browse/AMQ-4817 so that Hawtio can render ObjectMessages as text on the console.
