### ISSUE TITLE
Cannot open diagram view due to exception

### ISSUE THREAD

**Issue by syr** [hawtio/hawtio#664]
Hello,

I just tried hawtio on a Jboss eap 6.1 (7.2).

When I navigate to a specific route to open diagram view I get the following exception:

http://pastebin.com/NFuiqbE4

**Comment by vickrame** [comment]
Hi,

I have got the same problem with a different configuration when i try to generate 'route diagram' i have the same error  Caused by: java.lang.NoClassDefFoundError: Could not initialize class javax.xml.bind.DatatypeConverter

I modified the module.xml in this directory 'wildfly-8.2.0.Final\modules\system\layers\base\javax\api\main' in order to add <path name="javax/xml/bind" /> but the error continues.

I have Widfly 8 and i'm using camel in 2.15.2 and hawtio 1.4.52.

Do you have some ideas?

**Comment by davsclaus** [comment]
You may need to use wildfly-camel when using wildfly.
https://github.com/wildfly-extras/wildfly-camel

And there is also a hawtio-wildfly module you can use to install hawtio as a WAR
https://github.com/hawtio/hawtio/tree/master/hawtio-wildfly
