### ISSUE TITLE
Customize layout of hawtio UI

### ISSUE THREAD

**Issue by mitnpatel** [hawtio/hawtio#666]
I was wondering is there any way that I can customize UI of hawtio-web? I did some research but I did not find anything helpful.  

hawtio-web is my base. It comes with nice login page (https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/app/core/html/login.html)
Is there any way that I can have my own login.html instead of default login.html(from hawtio-web) so I can have full control of html layout and style. 

I was also wondering that how can in take control of html layout of index.html. For example how can I add new item in https://github.com/hawtio/hawtio/blob/master/hawtio-web/src/main/webapp/index.html#L69  , remove hawtio logo from top left corner, styling of whole page.

**Comment by sekaijin** [comment]
Hello
There is one thing I do not understand with the redhat plugin.

I use hawtio under osgi. I try to create my own branding.
I took "hawtio-redhat-fuse-branding" as model.

but when I deploy this plugin in karaf, hawtio retains its default branding.

I need to open hawtio preferences in my browser to see the RedHat branding is available.

In my business I have a karaf custom distribution and I would to make of my hawtio branding as default.
I did not find anything in the documentation about it.

A+JYT

**Comment by gashcrumb** [comment]
@sekaijin Best to open a new issue rather than comment on a 2 year old one :-)

The Red Hat branding plugin specifically checks to see if the user has a theme/branding stored or not, and if it doesn't will apply it as a default:

* Branding -> https://github.com/hawtio/hawtio/blob/master/hawtio-redhat-fuse-branding/src/main/webapp/plugin/js/plugin.js#L34-L36
* Theme -> https://github.com/hawtio/hawtio/blob/master/hawtio-redhat-fuse-branding/src/main/webapp/plugin/js/plugin.js#L20-L22

You would need to do the same in your own branding/theme plugin, you may even want to check and see if the branding/theme is set to Red Hat already and change it if you want to ensure the console always uses your branding.  Another option would be to just uninstall the Red Hat theme bundle.

**Comment by sekaijin** [comment]
Hi

Claus Ibsen pointed me to this direction.
Yesterday I've opened this code and I found.

Again thank you for your help.
A+JYT

**Comment by MariuszHxGNMIN** [comment]
Hi 
Is there any way to remove default branding and themes? especially the "Example" one... I have build mu own branding plugin based on red hat fuse and it works fine but no I would like to remove the example one or make my plugin as default theme
