### ISSUE TITLE
Store preferences server-side

### ISSUE THREAD

**Issue by gashcrumb** [hawtio/hawtio#679]
Currently we store all preferences in the browser local storage.  Ideally though we should store these on the server per-user so that if a user switches browsers their settings will be persistent.

**Comment by PawelJ-PL** [comment]
+1

**Comment by tadayosi** [comment]
@alexkieling Why did you close it?  I think it's still relevant and important as I see some customer request this feature.

**Comment by mottati** [comment]
+1

There is great value for us of to having some sort of server side configuration mechanism. We use Hawtio to provide developer JMX access to multiple services that our developers test against. Currently we have about 10 services that developers may need to examine. If we could pre-configure the JMX connections, and just have them show up when users to to that page, it would greatly reduce the friction that currently exists. 

As it stands now, we have to document all of the arcane Jolokia URLs they need to cofigure to get this access. Because the information is stored in browser cookies, this information does not persist across machines, or even browsers on a single machine.  Having a mechanism to preconfigure to preconfigure  JMX connection information would be a tremendous time saver for all of our users. 

Even something as simple as a Java system property name pattern would suffice for our use case.

e.g. something like -Djmx.connection.NAME=http://foo.con:8778/jolokia

would create a connection <NAME> pointing to the URL http://foo.con:8778/jolokia
